version: '3'
services:
  react-app:
    build:
      dockerfile: Dockerfile.dev
      context: ./react-app
    ports:
      - '4000:3000'
    volumes:
      - /app/node_modules
      - ./react-app:/app